container:
  image: gcc:latest

linux_task:
  script:
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release ${CMAKE_OPTIONS} && cmake --build . -- -j2
    - file ./nb
    - ./nb
    - |
      if [[ "${CODE_COVERAGE}" = "true" ]]; then
        cmake --build . --target lcov
      fi
