
# examples from:
# * https://github.com/chux0519/pegasocks/blob/master/.cirrus.yml
linux_task:
  container:
    matrix:
    - image: ubuntu:18.04
    - image: ubuntu:20.04

  install_script:
    - apt update && apt upgrade -y
    - DEBIAN_FRONTEND=noninteractive apt install -y cmake ninja-build build-essential

  build_script:
    - cd build
    - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release 
    - cmake --build . -- -j2

  test_script:
    - file ./nb
    - ./nb
