linux_task:
  container:
    image: gcc:latest
  task:
    script:
      - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi # make sure CXX is correctly set
      - uname -a # show OS/compiler version
      - $CXX --version
      - cd build  # build
      - cmake .. -DCMAKE_BUILD_TYPE=Release ${CMAKE_OPTIONS} && cmake --build . -- -j2

      # check file
      - file ./nb

      # run test
      - ./nb

      # coverage
      - |
        if [[ "${CODE_COVERAGE}" = "true" ]]; then
          cmake --build . --target lcov
        fi
